### ISSUE TITLE
upload through somo not playing. 

### ISSUE THREAD

**Issue by MangNPB** [didiatworkz/screenly-ose-monitoring#60] opened 2021-01-28 14:43 UTC
i have current screenly ose Sprint 10.1 Release. fresh install of somo. upload and multiupload seem to work but asset is not playing. switching to web interface i can disable the asset but when re-enable it cause this error: "Server Error: int() argument must be a string or a number, not 'NoneType'" 

uploaded 3 videos size 12mb, 30 mb, and 34mb - upload is a lot faster than web interface... but the 34mb didn't make it into the system even though it show as done. 

further inspection: start time is not set properly (asset uploaded in early AM and set start time at PM. Duration is not set correctly (default all  upload at 10 second) which is not the actual duration

uploaded the same 3 files via web interface (screenly ose) and they all goes in fine and the suspected speed and all play as normal.

**Comment by didiatworkz** [comment] 2021-01-28 17:32
Hello @MangNPB 
First of all, cool that you use SOMO :)
But I don't understand where the error "Server Error: int() argument must be a string or a number, not 'NoneType'" appears in your description?
Is it directly on the screenly player or in SOMO?

For the uploads, I would need to know from you where this happened, since the technique in the multiuploader is different than when you do the whole thing from the player menu.

About the date, that is known and is on my list https://github.com/didiatworkz/screenly-ose-monitoring/projects/4

The thing with the duration is again important, with which uploader this happened.

Regards,
didiatworkz

**Comment by MangNPB** [comment] 2021-01-28 18:00
Thank you for the response and thank you for your creation.   Your project makes life at the open source much easier.  Upload seem to have the same problem using both multilayer and single player "add asset" at the player menu.  Upload display seem fine and complete with some files show up on the assets list to be play by it will never play no matter what i do.  Switching to screenly ose web ui i can see the assets too but can't get any to play.  Disable assets works but when i try to enable them i get the long error message above and assets will stay disable. 

When using the screenly ose webui to upload everything works fine.

**Comment by didiatworkz** [comment] 2021-01-28 18:27
Hey @MangNPB 

I can reproduce the error... 
When you upload video the default duration time will normally set to the time in sec of the video
That's not happened at the moment - I will fix this

Regards,
didiatworkz

**Comment by didiatworkz** [comment] 2021-01-28 22:01
Hey @MangNPB 

I found the issue and fixed it - I will test it tomorrow and release it when everything is ok

**Comment by MangNPB** [comment] 2021-01-29 16:54
I do not know if this is related to the upload above but also found that the close button once upload is completed is not responding or doing anything.

**Comment by MangNPB** [comment] 2021-01-30 16:18
Update on fixes that is still broken for uploading mp4 videos. the fix works great for photos but for uploading video we have the following behaviors that ended up with the same broken result:

Single player upload: upload window abruptly closed when it seems like the process is done but upon refreshing the page there is no newly uploaded asset /assets to be found on play list in either SOMO or Screenly web ui.

Multiplayer upload: Up on what it seems like a completed upload the "reload" button shows up but on inspecting of SOMO single player list and Screenly web UI there is also no newly uploaded asset/s to be found. 

Mang

**Comment by didiatworkz** [comment] 2021-01-30 17:17
Hello @MangNPB 
can you tell me how big the file(s) are?
Which upload size do you configure in the settings and can you take a screenshot from the settings page with all versions of the scripts?

Btw: I tested the upload with up to 500MB mp4 files without any problems yet.

didiatworkz

**Comment by MangNPB** [comment] 2021-01-30 20:06
Hello again. 
The size in setting i set is 200mb. file size ranges from 12mb to 74 mb. all of them fail. 

![image](https://user-images.githubusercontent.com/44915183/106366815-6dedf200-630c-11eb-9fd9-4d5e7f329950.png)

**Comment by didiatworkz** [comment] 2021-01-30 20:20
Hey @MangNPB 
do you use raspbian stretch of the server and on the players?

Best
didiatworkz

**Comment by MangNPB** [comment] 2021-01-30 20:23
yes, it's the image from screenly. Should i put it on buster?

Mang

**Comment by didiatworkz** [comment] 2021-01-30 20:43
Hey @MangNPB 
I will test your configuration tomorrow and hopefully find the issue. I have done all the tests so far with buster.
Let's see what comes out.
I will keep you informed 

Best
didiatworkz

**Comment by MangNPB** [comment] 2021-01-30 20:59
Greatly appreciate all the efforts!

Magn

**Comment by MangNPB** [comment] 2021-01-31 03:14
I have tried to manual install Screenly OSE on Buster and no matter how i try i keep getting a python packing error that prevent the installation from being complete. Just wondering how did you get yours to run on buster? the latest image they have is only on stretch.

Mang

**Comment by didiatworkz** [comment] 2021-01-31 10:15
Hello @MangNPB 
when you run into the same error as me in the past (Python OpenSSL issue) you can read the solution here: https://github.com/Screenly/screenly-ose/issues/1264

If you run in another errors, paste the console output here to identify the issue - But normally that's a Screenly OSE problem and not a problem from my script 😉 
I'm setting up a stretch at the moment - So stay tuned.

Best
dididatworkz

**Comment by didiatworkz** [comment] 2021-01-31 14:24
Hello @MangNPB 

I found the problem and fixed it - Please reinstall SOMO with the command: `bash <(curl -sL https://git.io/JttTW)`
As an extra I implement a better error handling for uploads.
I close the issue.

Best
didiatworkz

PS: Please close the issue at Screenly-OSE (Issues #1486)

**Closed by didiatworkz** 2021-01-31 14:24 UTC
Labels: bug

**Comment by MangNPB** [comment] 2021-01-31 15:12
Thank you very much, DidiaWorkz. You are quite a life saver! If I need any private projects done in the future would you be available? My email is @gmail.com with the handle above. Let's exchange contact if you are interested. 

Once again thank you for all your helps.

Mang
